# Generated by Django 3.0.6 on 2020-05-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='destinasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('alamat', models.TextField()),
                ('htm', models.IntegerField()),
                ('jambuka', models.TextField()),
                ('fasilitas', models.TextField()),
                ('deskripsi', models.TextField()),
                ('link', models.CharField(max_length=50)),
            ],
        ),
    ]
