# Generated by Django 3.0.6 on 2020-06-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaftarForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topik', models.CharField(max_length=50)),
                ('deskripsi_topik', models.CharField(max_length=140)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
