# Generated by Django 3.0.6 on 2020-06-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Akun',
        ),
    ]
