# Generated by Django 3.0.6 on 2020-06-07 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_keranjang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penjual_order', models.CharField(max_length=50)),
                ('pembeli_order', models.CharField(max_length=50)),
                ('status_order', models.CharField(max_length=20)),
                ('jumlah_item_order', models.IntegerField()),
                ('kode_item_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Dagangan', unique=True)),
            ],
        ),
    ]
