# Generated by Django 3.0.6 on 2020-06-07 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0007_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dagangan',
            name='penjual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='keranjang',
            name='kode_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Dagangan'),
        ),
        migrations.AlterField(
            model_name='keranjang',
            name='pemilik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='order',
            name='kode_item_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Dagangan'),
        ),
    ]
