# Generated by Django 3.0.6 on 2020-06-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20200607_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dagangan',
            name='gambar_barang',
            field=models.TextField(default='https://via.placeholder.com/500x500.jpg?text=no+image'),
        ),
    ]
