# Generated by Django 3.0.6 on 2020-06-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20200607_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='dagangan',
            name='deskripsi_barang',
            field=models.TextField(blank=True, null=True),
        ),
    ]
