# Generated by Django 3.0.6 on 2020-06-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_dagangan_deskripsi_barang'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kota_asal',
            field=models.CharField(default='belum ditentukan', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='kota_tujuan',
            field=models.CharField(default='belum ditentukan', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='pengiriman',
            field=models.CharField(default='J&T', max_length=20),
        ),
    ]
