# Generated by Django 3.0.6 on 2020-05-31 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='langkah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('konten', models.TextField(null=True)),
                ('thumbnail', models.TextField(default='https://via.placeholder.com/300x200.jpg?text=tidak+ada+gambar')),
            ],
        ),
        migrations.CreateModel(
            name='gambar_langkah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar_langkah', models.TextField()),
                ('gambar_desc', models.CharField(max_length=50)),
                ('langkah_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.langkah')),
            ],
        ),
    ]
