# Generated by Django 3.0.6 on 2020-05-31 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0003_auto_20200531_1807'),
    ]

    operations = [
        migrations.DeleteModel(
            name='link_galeri',
        ),
    ]
